# Setup the environment for this build.
# We include this Makefile using a relative path (contains a ".."),
# This is because no environment has been setup yet.
# After including this Makefile, paths outside this directory should be
# included using the `TOP` variable (example: $(TOP)/cobra/.
include ../make/setup_env.mk

PROG := cobra_terminal


