#!/bin/sh

# Generates a small Makefile used in the root of the output
# directory, to allow make to be started from there.
# The Makefile also allows for more convenient build of external modules.

# Usage
# $1 - src directory

if [ "${quiet}" != "silent_" ]; then
	echo "  GEN     Makefile"
fi

cat << EOF > Makefile
# Automatically generated by $0: don't edit
include $1/Makefile
EOF

