#!/bin/sh

# Generates a small makefile used in the root of the output
# directory, to allow make to be started from there.
# The makefile also allows for more convenient build of external modules.

# Usage
# $1 - src directory

if [ "${quiet}" != "silent_" ]; then
	echo "  GEN  makefile"
fi

cat << EOF > makefile
# Automatically generated by $0: don't edit
include $1/makefile
EOF

